############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "projects/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Team"
url = "team/"
weight = 4

[[main]]
name = "Resources"
weight = 5
hasChildren = true

[[main]]
parent = "Resources"
name = "Papers"
url = "papers/"

[[main]]
parent = "Resources"
name = "Posters"
url = "posters/"

[[main]]
parent = "Resources"
name = "Presentations"
url = "presentations/"

[[main]]
weight = 6
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pages"
name = "Authors"
url = "authors/"

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

[[main]]
parent = "Pages"
name = "404 Page"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
