############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "projects/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Team"
url = "team/"
weight = 4

[[main]]
name = "Resources"
weight = 5
hasChildren = true

[[main]]
parent = "Resources"
name = "Papers"
url = "papers/"

[[main]]
parent = "Resources"
name = "Posters"
url = "posters/"

[[main]]
parent = "Resources"
name = "Presentations"
url = "presentations/"
